// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SieuThiMini.DAL;

namespace SieuThiMini.DAL.Migrations
{
    [DbContext(typeof(SieuThiDbContext))]
    partial class SieuThiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SieuThiMini.DAL.Entites.DanhMuc", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenDanhMuc")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new { Id = "dm01", TenDanhMuc = "Sách" },
                        new { Id = "dm02", TenDanhMuc = "Điện thoại" },
                        new { Id = "dm03", TenDanhMuc = "Quần áo" },
                        new { Id = "dm05", TenDanhMuc = "Trang sức" }
                    );
                });

            modelBuilder.Entity("SieuThiMini.DAL.Entites.SanPham", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DanhMucId");

                    b.Property<int>("DonGia");

                    b.Property<int>("SoLuong");

                    b.Property<string>("TenSanPham")
                        .IsRequired();

                    b.Property<string>("XuatXu")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new { Id = "fg", DanhMucId = "dm01", DonGia = 4, SoLuong = 4, TenSanPham = "fg", XuatXu = "f" },
                        new { Id = "er", DanhMucId = "dm05", DonGia = 5, SoLuong = 5, TenSanPham = "df", XuatXu = "fg" },
                        new { Id = "sp13", DanhMucId = "dm01", DonGia = 5000000, SoLuong = 15, TenSanPham = "Tivi lg", XuatXu = "Sony" },
                        new { Id = "sp0999", DanhMucId = "dm01", DonGia = 20000, SoLuong = 20, TenSanPham = "Cẩm nang làm xau", XuatXu = "Kim Đồng" },
                        new { Id = "sp103", DanhMucId = "dm01", DonGia = 500000, SoLuong = 9, TenSanPham = "Dây chuyền bạc", XuatXu = "Việt Nam" },
                        new { Id = "sp043", DanhMucId = "dm01", DonGia = 300000, SoLuong = 30, TenSanPham = "Nokia1202", XuatXu = "Trung Quốc" },
                        new { Id = "sp089", DanhMucId = "dm01", DonGia = 5000000, SoLuong = 15, TenSanPham = "Tivi", XuatXu = "Sony" },
                        new { Id = "sp109", DanhMucId = "dm05", DonGia = 500000, SoLuong = 9, TenSanPham = "Dây chuyền bạc", XuatXu = "Việt Nam" },
                        new { Id = "sp01", DanhMucId = "dm01", DonGia = 10000, SoLuong = 10, TenSanPham = "Lập trình Windows nâng cao", XuatXu = "HUI" },
                        new { Id = "sp02", DanhMucId = "dm01", DonGia = 20000, SoLuong = 20, TenSanPham = "Cẩm nang làm đẹp", XuatXu = "Kim Đồng" },
                        new { Id = "sp03", DanhMucId = "dm02", DonGia = 14000000, SoLuong = 17, TenSanPham = "iPhone5", XuatXu = "US" },
                        new { Id = "sp04", DanhMucId = "dm02", DonGia = 300000, SoLuong = 30, TenSanPham = "Nokia1202", XuatXu = "Trung Quốc" },
                        new { Id = "sp05", DanhMucId = "dm03", DonGia = 100000, SoLuong = 50, TenSanPham = "Áo sơ mi nam", XuatXu = "Việt Nam" },
                        new { Id = "sp06", DanhMucId = "dm03", DonGia = 350000, SoLuong = 24, TenSanPham = "Quần Jeans", XuatXu = "Việt Nam" },
                        new { Id = "sp09", DanhMucId = "dm05", DonGia = 25000000, SoLuong = 3, TenSanPham = "Mắt kính", XuatXu = "Việt Nam" },
                        new { Id = "sp10", DanhMucId = "dm05", DonGia = 500000, SoLuong = 9, TenSanPham = "Dây chuyền bạc", XuatXu = "Việt Nam" }
                    );
                });

            modelBuilder.Entity("SieuThiMini.DAL.Entites.SanPham", b =>
                {
                    b.HasOne("SieuThiMini.DAL.Entites.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId");
                });
#pragma warning restore 612, 618
        }
    }
}
